name: Daily Report

on:
  schedule:
    - cron: '0 23 * * *'  # 新設定 = UTC 23:00 = 隔天 JST 8:00
  workflow_dispatch:

jobs:
  send_report:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up Render service
        run: |
          curl https://line-bot-reporter.onrender.com/

      - name: Wait for service to wake up
        run: sleep 30

      - name: Send report
        run: |
          curl https://line-bot-reporter.onrender.com/send_report
