name: Daily Report

on:
  schedule:
    - cron: '05 5 * * *'  # UTC 05:05 = JST 14:05，預計實際執行在 JST 14:30
  workflow_dispatch:      

jobs:
  send_report:
    runs-on: ubuntu-latest
    
    steps:
      - name: Wake up Render service
        run: |
          curl https://line-bot-reporter.onrender.com/
          sleep 45  # 給予更多時間啟動
      
      - name: Send report trigger
        run: |
          curl https://line-bot-reporter.onrender.com/send_report
