name: Daily Report

on:
  schedule:
    - cron: '25 0 * * *'  # UTC 00:25 = JST 9:25
  workflow_dispatch:      

jobs:
  send_report:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up Render service
        run: |
          curl https://line-bot-reporter.onrender.com/
          sleep 30  # 等待 Render 服務完全啟動
          
      - name: Send report trigger
        run: |
          curl https://line-bot-reporter.onrender.com/send_report
