name: Daily Report

on:
  schedule:
    - cron: '00 22 * * *'  # UTC 22:00 = JST 07:00，給予2小時的緩衝時間
  workflow_dispatch:      

jobs:
  send_report:
    runs-on: ubuntu-latest
    
    steps:
      - name: Wake up Render service
        run: |
          curl https://line-bot-reporter.onrender.com/
          sleep 45  # 給予更多時間啟動
      
      - name: Send report trigger
        run: |
          curl https://line-bot-reporter.onrender.com/send_report
