name: Daily Report

on:
  schedule:
    - cron: '52 23 * * *'  # UTC 23:52 = JST 08:52，預計實際執行在 JST 09:00
  workflow_dispatch:      

jobs:
  send_report:
    runs-on: ubuntu-latest
    
    steps:
      - name: Wake up Render service
        run: |
          curl https://line-bot-reporter.onrender.com/
          sleep 45  # 給予更多時間啟動
      
      - name: Send report trigger
        run: |
          curl https://line-bot-reporter.onrender.com/send_report
